apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadxnba7176-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadxnba7176-tenant-component
    app.kubernetes.io/part-of: loadxnba7176-tenant-app
  name: loadxnba7176-tenant-component
  namespace: loadxnba7176-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadxnba7176-tenant-component
    weight: null
status: {}
