apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadxnba7176-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadxnba7176-tenant-component
    app.kubernetes.io/part-of: loadxnba7176-tenant-app
  name: loadxnba7176-tenant-component
  namespace: loadxnba7176-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: loadxnba7176-tenant-component
status:
  loadBalancer: {}
